### ISSUE TITLE
Change the blueprint of the masthead

### ISSUE THREAD

**Issue by thierry4cta** [cta-int/Frontender-Platform#17]
┆Attachments: <a href="https:&#x2F;&#x2F;trello-attachments.s3.amazonaws.com&#x2F;5bb5d91a0c0442795c489a0a&#x2F;5bb5fa238d3a771ad2be0b60&#x2F;09cad4df93cf38cf2d5367fffdb53a60&#x2F;masthead.html">masthead.html</a>

**Comment by thierry4cta** [comment]
<ul class="fx menu menu--responsive">
<li><a class="menu__item " href="/en/">Home</a></li>
<li><a class="menu__item" href="/en/about-cta">About CTA</a></li>
<li><a class="menu__item" target="_blank" href="http://spore.cta.int/">Spore</a></li>
<li><a class="menu__item" target="_blank" href="http://ictupdate.cta.int/">ICT Update</a></li>
<li><a class="menu__item" target="_blank" href="https://publications.cta.int/">Publications</a></li>
<li><a class="menu__item" href="/en/working-with-cta">Working with CTA</a></li>
<li><a class="menu__item" href="/en/press">Press</a></li>
<li><a class="menu__item" href="/en/contact">Contact</a></li>
</ul>

<ul class="list--inline  |  menu  |  site-navigation__menu">
<li><a class="menu__item" href="/en/youth">Youth</a></li>
<li><a class="menu__item" href="/en/digitalisation">Digitalisation</a></li>
<li><a class="menu__item" href="/en/climate">Climate</a></li>
<li><a class="menu__item" href="/en/gender">Gender</a></li>
<li><a class="menu__item" href="/en/events">Events</a></li>
<li><a class="menu__item" href="/en/projects">Projects</a></li>
<li><a class="menu__item" href="/en/impact-stories">Impact</a></li>
</ul>

**Comment by thierry4cta** [comment]
`<ul class="fx menu menu--responsive">
<li><a class="menu__item " href="/en/">Home</a></li>
<li><a class="menu__item" href="/en/about-cta">About CTA</a></li>
<li><a class="menu__item" target="_blank" href="http://spore.cta.int/">Spore</a></li>
<li><a class="menu__item" target="_blank" href="http://ictupdate.cta.int/">ICT Update</a></li>
<li><a class="menu__item" target="_blank" href="https://publications.cta.int/">Publications</a></li>
<li><a class="menu__item" href="/en/working-with-cta">Working with CTA</a></li>
<li><a class="menu__item" href="/en/press">Press</a></li>
<li><a class="menu__item" href="/en/contact">Contact</a></li>
</ul>
                    
<ul class="list--inline  |  menu  |  site-navigation__menu">
<li><a class="menu__item" href="/en/youth">Youth</a></li>
<li><a class="menu__item" href="/en/digitalisation">Digitalisation</a></li>
<li><a class="menu__item" href="/en/climate">Climate</a></li>
<li><a class="menu__item" href="/en/gender">Gender</a></li>
<li><a class="menu__item" href="/en/events">Events</a></li>
<li><a class="menu__item" href="/en/projects">Projects</a></li>
<li><a class="menu__item" href="/en/impact-stories">Impact</a></li>
</ul>`

**Comment by babsgosgens** [comment]
@thierry4cta graag de json output, dan kunnen we het vandaag nog deployen.
```json
{}
```

**Comment by thierry4cta** [comment]
"containers": [
		{
			"fe-id": "c8df5a8d80aff0bc",
			"name": {
				"en": "Masthead"
			},
			"description": {
				"en": "CTA's main masthead"
			},
			"template": "containers/global/group/group.html.twig",
			"template_config": {
				"config": {
					"label": {
						"en": "Settings"
					},
					"controls": {
						"container_tag": {
							"hidden": "0",
							"access": "all",
							"type": "hidden",
							"value": "header",
							"label": {
								"en": "Hidden"
							}
						},
						"container_class": {
							"hidden": "0",
							"access": "all",
							"type": "hidden",
							"value": "masthead",
							"label": {
								"en": "Hidden"
							}
						}
					}
				},
				"containers": [
					{
						"fe-id": null,
						"name": {
							"en": "Network navigation"
						},
						"description": {
							"en": ""
						},
						"template": "modules/network-navigation/network-navigation.html.twig",
						"template_config": {
							"mobile": {
								"label": {
									"en": "Mobile Settings"
								},
								"controls": {
									"menu_label": {
										"hidden": "0",
										"access": "all",
										"type": "text",
										"value": {
											"en": "Menu",
											"fr": "Menu"
										},
										"label": {
											"en": "Menu label (mobile only)"
										}
									},
									"show_menu_label": {
										"value": 0,
										"label": {
											"en": "Show menu label (mobile only)"
										},
										"hidden": "0",
										"access": "all",
										"type": "list",
										"options": [
											{
												"value": 0,
												"label": {
													"en": "Hide"
												}
											},
											{
												"value": 1,
												"label": {
													"en": "Show"
												}
											}
										]
									},
									"menu_icon": {
										"hidden": "0",
										"access": "all",
										"type": "list",
										"value": "home",
										"label": {
											"en": "Menu icon (mobile only)"
										},
										"options": [
											{
												"label": {
													"en": "Leaf"
												},
												"value": "leaf"
											},
											{
												"label": {
													"en": "Home"
												},
												"value": "home"
											}
										]
									}
								}
							},
							"links": {
								"label": {
									"en": "Network navigation"
								},
								"controls": {
									"links": {
										"hidden": "0",
										"access": "all",
										"type": "compound",
										"value": [
											{
												"label": {
													"en": "About CTA",
													"fr": "À propos du CTA"
												},
												"page": "about-cta",
												"id": ""
											},
											{
												"label": {
													"en": "Spore",
													"fr": "Spore"
												},
												"page": "http://spore.cta.int/fr/",
												"id": ""
											},
											{
												"label": {
													"en": "ICT Update",
													"fr": "ICT Update"
												},
												"page": "http://ictupdate.cta.int/?lang=fr",
												"id": ""
											},
											{
												"label": {
													"en": "Publications",
													"fr": "Publications"
												},
												"page": "https://publications.cta.int/fr/",
												"id": ""
											},
											{
												"label": {
													"en": "Working with CTA",
													"fr": "Travailler avec le CTA"
												},
												"page": "working-with-cta",
												"id": ""
											},
											{
												"label": {
													"en": "Press",
													"fr": "Presse"
												},
												"page": "press",
												"id": ""
											},
											{
												"label": {
													"en": "Contact",
													"fr": "Contact"
												},
												"page": "contact",
												"id": ""
											}
										],

**Comment by thierry4cta** [comment]
@babsgosgens  JSON output hierboven

**Comment by thierry4cta** [comment]
Was a bit fast to close the ticket

**Comment by babsgosgens** [comment]
@thierry4cta here is an overview of Github markdown, it is really helpful when code samples/examples are formatted as code:
https://guides.github.com/features/mastering-markdown/

**Comment by thierry4cta** [comment]
Seems I can't have a different URL in Fr and English - so I changed the network navigation again

**Comment by JaspervRijbroek** [comment]
@thierry4cta On which page did you change the masthead?
Just copied the one from impact stories and I don't see any changes.

**Comment by thierry4cta** [comment]
Impact stories UAT


Best regards,

[cid:image001.jpg@01D4071A.22F199B0]

Thierry​



Lewyllie


Web Programme Coordinator

TEL

 +31 (0) 317 467106 (direct) |

SKYPE cta.lewyllie.thierry<skype:cta.lewyllie.thierry>


P.O.Box 380, 6700 AJ Wageningen, The Netherlands


www.cta.int<http://www.cta.int/>


Technical Centre for Agricultural and Rural Cooperation

ACP‑EU Cotonou Agreement

[http://branding.cta.int/wp-content/uploads/2018/04/face-book.jpg]<https://www.facebook.com/CTApage/>

[http://branding.cta.int/wp-content/uploads/2018/04/twitter.jpg]<https://twitter.com/ctaflash>

[http://branding.cta.int/wp-content/uploads/2018/04/linkdin.jpg]<https://www.linkedin.com/company/technical-centre-for-agricultural-and-rural-cooperation-acp-eu-cta-/>

[http://branding.cta.int/wp-content/uploads/2018/04/instagram.jpg]<https://www.instagram.com/ctaflash/>

**Comment by thierry4cta** [comment]
Seems I had to approve the change to propagate to the production environment



Best regards,

[cid:image001.jpg@01D4071A.22F199B0]

Thierry​



Lewyllie


Web Programme Coordinator

TEL

 +31 (0) 317 467106 (direct) |

SKYPE cta.lewyllie.thierry<skype:cta.lewyllie.thierry>


P.O.Box 380, 6700 AJ Wageningen, The Netherlands


www.cta.int<http://www.cta.int/>


Technical Centre for Agricultural and Rural Cooperation

ACP‑EU Cotonou Agreement

[http://branding.cta.int/wp-content/uploads/2018/04/face-book.jpg]<https://www.facebook.com/CTApage/>

[http://branding.cta.int/wp-content/uploads/2018/04/twitter.jpg]<https://twitter.com/ctaflash>

[http://branding.cta.int/wp-content/uploads/2018/04/linkdin.jpg]<https://www.linkedin.com/company/technical-centre-for-agricultural-and-rural-cooperation-acp-eu-cta-/>

[http://branding.cta.int/wp-content/uploads/2018/04/instagram.jpg]<https://www.instagram.com/ctaflash/>
