### ISSUE TITLE
Give Babs rights to create and edit Wiki pages

### ISSUE THREAD

**Issue by babsgosgens** [cta-int/Frontender-Platform#18]
@thierry4cta can you please give me sufficient rights so that I can create and maintain wiki pages and projects?

**Comment by thierry4cta** [comment]
@babsgosgens can you confirm you have the rights needed

**Comment by babsgosgens** [comment]
👍

**Comment by thierry4cta** [comment]
Added the Brickson team and Babs as collaborator
